### ISSUE TITLE
MCP tool doesn't show up in Claude (macOS)

### ISSUE THREAD

**Issue by ibehnam** [MarkusPfundstein/mcp-gsuite#12]
I followed the instructions and created `.accounts.json` and `.gauth.json` files in `~/Library/Application Support/Claude`. I also entered the info from Google console in those files. But the MCP tool doesn't show up in the app even after restarting it.

**Comment by MarkusPfundstein** [comment]
You can see what happens by looking at the mcp log files. Maybe something is wrong and an error is thrown during startup.
Check for instance the file: `~/Library/Logs/Claude/mcp-server-mcp-gsuite.log`

**Comment by ibehnam** [comment]
@MarkusPfundstein Thanks, here's what the log says:

```
╰─❯ cat ~/Library/Logs/Claude/mcp-server-mcp-gsuite.log
  × No solution found when resolving tool dependencies:
  ╰─▶ Because the current Python version (3.12.3) does not satisfy
      Python>=3.13 and all versions of mcp-gsuite depend on Python>=3.13, we
      can conclude that all versions of mcp-gsuite cannot be used.
      And because you require mcp-gsuite, we can conclude that your
      requirements are unsatisfiable.
```

I upgraded Python to 3.13 but now I get this error:

```
╰─❯ # Follow logs in real-time
    tail -n 20 -f ~/Library/Logs/Claude/mcp*.log


==> /Users/behnam/Library/Logs/Claude/mcp-server-@executeautomation-playwright-mcp-server.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-@modelcontextprotocol-server-sequential-thinking.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-arxiv-mcp-server.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-brave-search.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-filesystem.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-mcp-gsuite.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-memory.log <==
Knowledge Graph MCP Server running on stdio

==> /Users/behnam/Library/Logs/Claude/mcp-server-playwright.log <==

==> /Users/behnam/Library/Logs/Claude/mcp-server-sequential-thinking.log <==

==> /Users/behnam/Library/Logs/Claude/mcp.log <==
2024-12-21T16:38:09.207Z [info] Connected to MCP server playwright!
2024-12-21T16:38:09.207Z [info] Connected to MCP server sequential-thinking!
2024-12-21T16:38:09.208Z [info] Connected to MCP server mcp-gsuite!
2024-12-21T16:38:09.208Z [info] Connected to MCP server @executeautomation-playwright-mcp-server!
2024-12-21T16:38:09.209Z [info] Connected to MCP server @modelcontextprotocol-server-sequential-thinking!
2024-12-21T16:38:14.102Z [info] MCP server mcp-gsuite disconnected. For troubleshooting guidance, please visit our [debugging documentation](https://modelcontextprotocol.io/docs/tools/debugging)
2024-12-21T16:40:02.433Z [info] Attempting to connect to MCP server brave-search...
2024-12-21T16:40:02.436Z [info] Attempting to connect to MCP server filesystem...
2024-12-21T16:40:02.436Z [info] Attempting to connect to MCP server playwright...
2024-12-21T16:40:02.437Z [info] Attempting to connect to MCP server sequential-thinking...
2024-12-21T16:40:02.437Z [info] Attempting to connect to MCP server mcp-gsuite...
2024-12-21T16:40:02.437Z [info] Attempting to connect to MCP server @executeautomation-playwright-mcp-server...
2024-12-21T16:40:02.437Z [info] Attempting to connect to MCP server @modelcontextprotocol-server-sequential-thinking...
2024-12-21T16:40:02.445Z [info] Connected to MCP server brave-search!
2024-12-21T16:40:02.446Z [info] Connected to MCP server filesystem!
2024-12-21T16:40:02.446Z [info] Connected to MCP server playwright!
2024-12-21T16:40:02.447Z [info] Connected to MCP server sequential-thinking!
2024-12-21T16:40:02.448Z [info] Connected to MCP server mcp-gsuite!
2024-12-21T16:40:02.448Z [info] Connected to MCP server @executeautomation-playwright-mcp-server!
2024-12-21T16:40:02.450Z [info] Connected to MCP server @modelcontextprotocol-server-sequential-thinking!

==> /Users/behnam/Library/Logs/Claude/mcp-server-mcp-gsuite.log <==
Traceback (most recent call last):
  File "/Users/behnam/Library/Caches/uv/archive-v0/I7593nx0ZmZyrUuR5dRm-/bin/mcp-gsuite", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/behnam/Library/Caches/uv/archive-v0/I7593nx0ZmZyrUuR5dRm-/lib/python3.13/site-packages/mcp_gsuite/__init__.py", line 6, in main
    asyncio.run(server.main())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/behnam/Library/Caches/uv/archive-v0/I7593nx0ZmZyrUuR5dRm-/lib/python3.13/site-packages/mcp_gsuite/server.py", line 151, in main
    accounts = gauth.get_account_info()
  File "/Users/behnam/Library/Caches/uv/archive-v0/I7593nx0ZmZyrUuR5dRm-/lib/python3.13/site-packages/mcp_gsuite/gauth.py", line 37, in get_account_info
    with open('./.accounts.json') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './.accounts.json'

==> /Users/behnam/Library/Logs/Claude/mcp.log <==
2024-12-21T16:40:03.395Z [info] MCP server mcp-gsuite disconnected. For troubleshooting guidance, please visit our [debugging documentation](https://modelcontextprotocol.io/docs/tools/debugging)

==> /Users/behnam/Library/Logs/Claude/mcp-server-filesystem.log <==
Secure MCP Filesystem Server running on stdio
Allowed directories: [ '/users/behnam/desktop', '/users/behnam/downloads' ]

==> /Users/behnam/Library/Logs/Claude/mcp-server-brave-search.log <==
Brave Search MCP Server running on stdio

==> /Users/behnam/Library/Logs/Claude/mcp-server-sequential-thinking.log <==
Sequential Thinking MCP Server running on stdio

==> /Users/behnam/Library/Logs/Claude/mcp-server-@modelcontextprotocol-server-sequential-thinking.log <==
Sequential Thinking MCP Server running on stdio
```

Where should `.accounts.json` and `.gauth.json` be located? I tried moving them from `~/Library/Application Support/Claude` to `~` and it still didn't work.

**Comment by ibehnam** [comment]
Thanks, I updated to Python 3.13 and it worked.
